# Generated by Django 3.1.2 on 2020-10-09 19:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='carbonhydrates',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='fats',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='proteins',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe2ingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.ingredients'),
        ),
        migrations.AlterField(
            model_name='recipe2ingredient',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recipe2ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.recipes'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 9, 19, 13, 57, 249169, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
